{% set version = '2.2.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yaml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yaml_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yaml/yaml_{{ version }}.tar.gz
  sha256: 55bcac87eca360ab5904914fcff473a6981a1f5e6d2215d2634344d0ac30c546

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('yaml')"           # [not win]
    - "\"%R%\" -e \"library('yaml')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/viking/r-yaml/
  license: BSD_3_clause + file LICENSE
  summary: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<http://pyyaml.org/wiki/LibYAML>)
    for R.
  license_family: BSD

extra:
  recipe-maintainers:
    - croth1
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: yaml
# Type: Package
# Title: Methods to Convert R Data to YAML and Back
# Date: 2018-07-20
# Version: 2.2.0
# Suggests: RUnit
# Author: Jeremy Stephens [aut, cre], Kirill Simonov [aut], Yihui Xie [ctb], Zhuoer Dong [ctb], Hadley Wickham [ctb], Jeffrey Horner [ctb], reikoch [ctb], Will Beasley [ctb], Brendan O'Connor [ctb], Gregory R. Warnes [ctb]
# Maintainer: Jeremy Stephens <jeremy.f.stephens@vumc.org>
# License: BSD_3_clause + file LICENSE
# Description: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<http://pyyaml.org/wiki/LibYAML>) for R.
# URL: https://github.com/viking/r-yaml/
# BugReports: https://github.com/viking/r-yaml/issues
# NeedsCompilation: yes
# Packaged: 2018-07-24 19:09:41 UTC; stephej1
# Repository: CRAN
# Date/Publication: 2018-07-25 15:40:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
