travis:
  secure:
    BINSTAR_TOKEN: QNefgX7i8vvchouAu6cV2aFWk5DAi8NBIhmWhWl66R6dbEIPKtIk6q3iM36aLPA19s1CB21zoX/rmrA6sNoD5wQwasJ+C6lS5WrpxR5G/CA3fE/qQtwYXPKTyqQ66LLXIw6dH2GFadNC7fUVUo8gkkpBa3DKUiEPv87VxBu3N2tnfHkcrSvKBaaDH51ktKh3+fevz9PyY/Izdn9EZies5Gtq4GrSLeUJ0x6WDyJ0rSGzK+4ReHZmxu8f7TbhfV638DBE6JuAeG8l7hCRsz0rUQitkVqPXpuBm0S6FEiUKjtjlvG7cf5aV5U/yI/KWmb3NSrC0Gmbj0NG60lptWv6eUl1qo1B2Qu+Ex30Q/yikz+yLHRnfuKNpN+cyW2cJ4AonwesUdze+l7f2Eci93ZvqnRw23sXR5olZubGpNTTuZqF4Mx3rrsQ/bdw9wDiJY40jIc2DvUO6/Hx11NIzi3rbkDhpvWhAYFRlP+ACTiOuIB99rFKV+bh9I3/jCtDGkca87i3PyPvCOogVnF3NmpwbZuen4MK6ZQEyrWkW0GTMq5Hi5PDSnQdcZXOXbxGghP1+sLvfKM97YI2m7PHZQGr5lqq/EMkiBVJyBDPg+d60/Kjf0ygIM9nE7xw3jtJCTQV5eG8LRP0pOd34N/+Sew26UNXfoMwryRpjlhipseO1u8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
